#%RAML 1.0 DataType

type: object
description: 
properties:
  RecordTypeId?: string
  AQB__ContactId__r? : string
  AQB__Contact__c? : string
  AQB__EndDate__c? : string
  AQB__Ended__c? : string
  AQB__RelatedTo__c? : string
  AQB__RelatedName__c? : string
  AQB__Relationship__c? : string
  AQB__ReverseRelationship__c? : string
  AQB__StartDate__c? : string
  AQB__Started__c? : string
  AQB__Relationship_Type__c? : string
  AQB__Source__c? : string
