#%RAML 1.0 DataType

type: object
description: 
properties:
  AQB__Street__c : string
  AQB__Type__c : string
  AQB__City__c : string
  AQB__StreetLineOnex__c : string
  AQB__StreetLineTwox__c : string
  AQB__StreetLineThreex__c : string
  AQB__County__c : string
  AQB__Last_Use__c : string
  CreatedById : string
  AQB__StateProvince__c : string
  AQB__CountryId__c : string
  AQB__EmploymentExternalID__c : string
  AQB__Country__c : string
  AQB__Phone__c : string
  AQB__StateId__c : string
  AQB__PostalCode__c : string
  AQB__Address__c : string
  AQB__Fax__c : string
  AQB__Contact__c : string
