#%RAML 1.0 DataType

type: object
description: 
properties:
  AQB__ContactExternalID__c: string
  FirstName? : string
  LastName? : string
  MiddleName? : string
  AQB__MaidenName__c?:
    type: string
    required: false
    description: maiden name
  AQB__AddressInUseType__c? : string
  AQB__CAECategory__c? : string
  MailingAddress? : string
  MailingStreet? : string
  MailingCity? : string
  MailingState? : string
  MailingPostalCode? : string
  MailingCountry? : string
  AQB__DateofDeath__c? : string
  AQB__Deceased__c? : boolean
  AQB__EmailPreference__c? : string
  AQB__Gender__c? : string
  AQB__MaritalStatus__c? : string
  AQB__PlaceofBirth__c? : string
  Birthdate? : string
  Email? : string
  AQB__PersonalEmail__c? : string
  AQB__BusinessEmail__c? : string
  AQB__SchoolEmail__c?: string
  Salutation?: string
  AQB__SalutationLink__c?: string
  AQB__CountryId__c?: string
  AQB__County__c?: string
  AQB__Type__c? : string