#%RAML 1.0 DataType

type: object
description: 
properties:
  AQB__AccountDefaultCity__c?: string
  AQB__AccountDefaultCountry__c?: string
  AQB__AccountDefaultCounty__c?: string
  AQB__AccountDefaultZipCode__c?: string
  AQB__AccountExternalID__c: string
  Name?: string
  RecordTypeId?: string
  AQB__AccountDefaultStatus__c?: string
  AQB__AccountDefaultStreet__c?: string
  AQB__AccountDefaultStateId__c?: string
  AQB__AccountType__c?: string
  AQB__CAECategory__c?: string
  AQB__PrimaryContact__c?: string
  AQB__SecondaryContact__c?: string
  AQB__AccountStatus__c?: string
  AQB__Email__c?: string
  
