#%RAML 1.0 NamedExample

value:
-
  AQB__AccountDefaultCity__c: "Orange"
  AQB__AccountDefaultCountry__c: "United States"
  AQB__AccountDefaultCounty__c: "Orange"
  AQB__AccountDefaultZipCode__c: "92866-1005"
  AQB__AccountExternalID__c: "0000001"
  Name: "Chapman University"
  RecordTypeId: "0122E000000h0RDQAY"
  AQB__AccountDefaultStatus__c: "Good"
  AQB__AccountDefaultStreet__c: "6102 Darlington Ave"
  AQB__AccountDefaultStateId__c: "CA"
  AQB__AccountType__c: "Household"
  AQB__CAECategory__c: "Other Individual"
  AQB__PrimaryContact__c: "003P000001OMyhYIAT"
  AQB__SecondaryContact__c: "003P000001OMyhXIAT"
  AQB__AccountStatus__c: "Active"
  AQB__Email__c: "ncmidlin@yahoo.com"