#%RAML 1.0 NamedExample

value:
  -
    "AQB__LastYearofAttendance__c": "2020"
    "AQB__Institution__c": "a0u2E000009UhuSQAS"
    "AQB__FirstYearofAttendance__c": "2018"
    "AQB__Contact__c": "003P000001OLkhNIAT"
    "AQB__Campus__c": "Main/Orange Campus"
    "AQB__DegreeLevel__c": "Graduate"
    "AQB__School__c": "School of Business & Economics"
    "type": "AQB__Education__c"
    "AQB__HonoraryDegree__c": false
    "AQB__Graduation_Month__c": "May"
    "AQB__GraduationYear__c": "2020"
    "RecordTypeId": "0122E000000h0RrQAI"
    "AQB__Status__c": "Dismissal"