#%RAML 1.0 NamedExample

value:
-
  AQB__ContactExternalID__c: "0711456"
  FirstName: "Nancy"
  LastName: "Midlin"
  MiddleName: ""
  AQB__MaidenName__c: "stella"
  AQB__AddressInUseType__c: "Account Mailing"
  AQB__CAECategory__c: "Alumni"
  MailingAddress: "4128 Norton Ave"
  MailingStreet: "4128 Norton Ave"
  MailingCity: "Oakland"
  MailingState: "California"
  MailingPostalCode: "94602-4016"
  MailingCountry: "United States"
  AQB__DateofDeath__c: ""
  AQB__Deceased__c: false
  AQB__EmailPreference__c: "Personal Email"
  AQB__Gender__c: "F"
  AQB__MaritalStatus__c: "Married"
  AQB__PlaceofBirth__c: ""
  Birthdate:  "1961-11-28T00:00:00"
  Email: "ncmidlin@yahoo.com"
  AQB__PersonalEmail__c: "ncmidlin@yahoo.com"
  AQB__BusinessEmail__c: "ncmidlin@yahoo.com"
  AQB__SchoolEmail__c: "ncmidlin@yahoo.com"
  Salutation: "Ms."
  AQB__SalutationLink__c: "Ms."
  AQB__CountryId__c: "USA"
  AQB__County__c: "Alameda"
  AQB__Type__c: "Parent"