#%RAML 1.0 NamedExample

value:
-
  RecordTypeId: "0122E000000h0SVQAY"
  AQB__ContactId__r : "0000002"
  AQB__Contact__c : "0000002"
  AQB__EndDate__c : "1961-11-28T00:00:00"
  AQB__Ended__c : "1961-11-28T00:00:00"
  AQB__RelatedTo__c : "1601789"
  AQB__RelatedName__c : "Elisabeth Lynne Begando"
  AQB__Relationship__c : "Daughter"
  AQB__ReverseRelationship__c : "Mother"
  AQB__StartDate__c : "1994-07-10T00:00:00"
  AQB__Started__c : "On"
  AQB__Relationship_Type__c : "Family"
  AQB__Source__c : "Campus Solution"