%dw 2.0
output application/json
var obj =[payload]
---
obj map{
  "EMPLID": "00" ++ $."EMPLID",
  "ADDRESSLONG": $."ADDRESSLONG",
  "ADDRESS_TYPE": $."ADDRESS_TYPE",
  "ADDRESS2": $."ADDRESS2",
  "CITY": $."CITY",
  "ADDRESS1": $."ADDRESS1",
  "COUNTY": $."COUNTY",
  "ADDR_TYPE_SHORT": $."ADDR_TYPE_SHORT",
  "STATE_DESCR": $."STATE_DESCR",
  "LAST_UPDT_DTTM": $."LAST_UPDT_DTTM",
  "COUNTRY_CD": $."COUNTRY_CD",
  "EMPLID": $."EMPLID",
  "COUNTRY_NM": $."COUNTRY_NM",
  "ADDRESSLONG3": $."ADDRESSLONG3",
  "STATE": $."STATE",
  "POSTAL": $."POSTAL",
  "ADDRESSLINE": $."ADDRESSLINE"
}